### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [waltervoynarovsky/waltervoynarovsky.github.io#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages) : DONE
2. A public GitHub repository for your codebase : DONE
3. Use HTML & SCSS : DONE
4. Make good use of semantic HTML elements : DONE
5. Be responsive (mobile-first) and built with accessibility in mind : DONE
6. Code is highly readable (good naming and indented correctly) : DONE - Needs work

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Augusta-Course-Resources/blob/main/student-resources/00-slides/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 30 / 50  |
| Responsiveness       | 15 / 15  |
| Code Knowledge & Use | 10 / 20  |
| Readability          | 10 / 15  |
| Version Control      | 10 / 10  |
| Total Score          | 75 / 110 |

## Positive

As your first project, I think that this is a success, you have clearly enjoyed coding a website from a wireframe. If you ever need a break pick a website and try and recreate it. Or have a look on code-pen for some inspiration to add into your own designs.

The website looks great on mobile and almost matches the design. There are a couple of tweaks you will need to make mainly around the form you added, which is a great addition btw :). At the moment it has a `min-width: 450px;` which means on mobiles it overflows and causes some side-scrolling.

- You can always just add this in a media query, while you are there reduce the padding on the form as well.

Good use of Git and Github, keep on committing with meaningful messages.

You are demonstrating a solid understanding of the majority of topics we have covered so far, keep it up and keep on using BEM, SCSS, grid and flex :D.

## Constructive

- You have a `.DS_Store` file these are auto-generated, I can't remember why but you can have a google and see how to stop it. Alternatively, you can have a `.gitignore` in the project with `.DS_Store` inside it.
- Your form button looks a bit strange I think you will have to remove the background on the `span` and `svg`. I would reduce the width of it as well.
- You are inconsistent with nesting your SCSS. Being consistent will make your code easier to understand. You are grouping your styles into little blocks. I will give you demo of nesting below with the BEM points.

- Your BEM is a bit hit and miss which is fine as it takes practice.

  - names are lowercase hyphenated if multiple words. Camel casing is for JS.
    - e.g. `projectsHeader` -> `projects-header`
  - You can use multiple class names on your HTML elements if they have the same style. So you don't need `.project1__img` to `.project6__img` you can have `.project__img` that is used on those 6 HTML elements.
  - You want to avoid using any html css selectors with BEM, the rule is everything that is going to have specific styles needs a class name. Resets are the exception.

Let's compare HTML

```html
<footer>
  <div class="footer_links" id="footer">
    <a href="https://github.com/waltervoynarovsky">
      <img class="footer__img" alt="Github link" src="./images/github.png"
    /></a>
    <a href="https://www.linkedin.com/in/walter-wojnarowski-775691215/">
      <img
        alt="LinkedIn link"
        src="./images/vecteezy_linkedin-american-business-logo-social-media-icon-black_3692704.jpg"
    /></a>
    <a href="https://www.linkedin.com/in/walter-wojnarowski-775691215/">
      <img alt="CV link" src="./images/Asset 2.png"
    /></a>
  </div>
  <p>walterw@gmail.com</p>
</footer>

<!-- WOULD BE -->

<footer class="footer">
  <div class="footer__links" id="footer">
    <a class="footer__link" href="https://github.com/waltervoynarovsky">
      <img class="footer__img" alt="Github link" src="./images/github.png"
    /></a>
    <a class="footer__link" href="https://www.linkedin.com/in/walter-wojnarowski-775691215/">
      <img
        class="footer__img"
        alt="LinkedIn link"
        src="./images/vecteezy_linkedin-american-business-logo-social-media-icon-black_3692704.jpg"
    /></a>
    <a class="footer__link" href="https://www.linkedin.com/in/walter-wojnarowski-775691215/">
      <img class="footer__img" alt="CV link" src="./images/Asset 2.png"
    /></a>
  </div>
  <p class="footer__email">walterw@gmail.com</p>
</footer>
```

Lets compare scss.

```scss
footer {
  min-height: 50px;
  display: grid;
  justify-content: space-around;
  background-color: $color-black;
  margin: 1rem;
  padding: 1rem;

  .footer_links {
    background-color: $color-black;
    justify-content: center;
  }
  a {
    background-color: $color-black;
    text-decoration: none;
  }

  img {
    width: 35px;
    height: 35px;
    border-radius: 70%;
    align-items: center;
    align-self: center;
  }

  p {
    background-color: $color-black;
    color: $color-white;
    text-decoration: none;
    text-align: center;
  }
}

// WOULD BE

.footer {
  min-height: 50px;
  display: grid;
  justify-content: space-around;
  background-color: $color-black;
  margin: 1rem;
  padding: 1rem;

  &__links {
    background-color: $color-black;
    justify-content: center;
  }

  &__link {
    background-color: $color-black;
    text-decoration: none;
  }

  &__img {
    width: 35px;
    height: 35px;
    border-radius: 70%;
    align-items: center;
    align-self: center;
  }

  &__email {
    background-color: $color-black;
    color: $color-white;
    text-decoration: none;
    text-align: center;
  }
}
```

Please take these points further with your next project, use SCSS and the awesome features it gives you. Keep using BEM for naming as well.

Reach out if you do run into any problems.

---
